#cloud-config

coreos:
  etcd2:
    name: node1
    proxy: on
    listen-client-urls: http://10.0.1.101:2379,http://10.0.1.101:4001
    initial-cluster: node0=http://10.0.1.100:2380
  fleet:
    public-ip: 10.0.1.101
    etcd_servers: http://10.0.1.101:2379,http://10.0.1.101:4001
    metadata: region=coreos-cluster,disk1=true,cpu=e5-xeon,memory=32G,bigdisk=true,raid=0
  units:
    - name: media-md126p1.mount
      command: start
      content: |
        [Mount]
        What=/dev/md126p1
        Where=/media/md126p1
        Type=ext4
    - name: rpc-statd.service
      command: start
      enable: true
    - name: enp2s0f0.network
      runtime: true
      content: |
        [Match]
        Name=enp2s0f0

        [Network]
        Address=10.0.1.101/24
        Gateway=10.0.1.1
    - name: enp2s0f1.network
      runtime: true
      content: |
        [Match]
        Name=enp2s0f1

        [Network]
        Address=10.0.0.101/24
        Gateway=10.0.0.1
    - name: etcd2.service
      command: start
      enable: true
    - name: fleet.service
      command: start
      enable: true
hostname: "node1" 
users:
  - name: "jack"
    passwd: "$6$BSh2ltL4$gF2YU6zYuo49ZWwWO9ZxX.4tQ8gLHDMXwL0VbsG96hZpaEsE9gOa9ID4ET6ebLDl2orVAov0m0zgk6LSwXTM4/"
    groups:
      - "sudo"
      - "docker"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG8FWtQ0ynyf2z6P0HF/toALe2Qp9jeg3fxQQZ1qexV38gtrmBszGVXQP4bHX8Lpe4Svg+PxrchYsExrXts+PNYcHaPZhRi6WKmJ8FmlMp1HoKAVXJwV/+FzNia02kUeD9oOMrbndfP1u3ubhbnrRFrbrWpE3MhTV9KptvgDlGAqjjJ/zN7w3JxOnILxPTM7dtH5k0EKrz3h2Bjd6DZGH2MdHH1NFajM5gyFtn/dd2j/Xd38eXKzN8wvU5iusqXj6yVXa1HeDklbwj9kRxFwONTrv3EDi4v9eUqfCAuLbe5rnHq9wg50oS2BdlKqOTXxIYbUXcKz6hkxK8WOa/Ywb3 jack@Jacks-MacBook-Pro.local"
write_files:
  - path: "/etc/environment"
    permissions: "0644"
    owner: "root"
    content: |
      COREOS_PUBLIC_IPV4=10.0.1.101
      COREOS_PRIVATE_IPV4=10.0.0.101
      COREOS_REGISTRY=node0:5000
      LOCAL_DISK1=/media/md126p1
      RAID_DISK=/media/md126p1
      
write_files:
  - path: "/etc/hosts"
    permissions: "0644"
    owner: "root"
    content: |
      10.0.1.100  node0
      10.0.1.101  node1
      10.0.1.102  node2
write_files:
  - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
    content: |
        [Service]
        Environment="DOCKER_OPTS=--insecure-registry 10.0.0.0/16"
write_files:
  - path: /home/jack/.docker/config.json
    permissions: "0744"
    owner: "jack"
    content: |
        { "auths": { "node0:5000": { "auth": "amFjazpodWp1bmxpbnV4", "email": "iamjackhu@163.com" } } }